import React, { useState } from 'react';

interface ManifestViewerProps {
  manifest: any;
  isLoading?: boolean;
}

export default function ManifestViewer({ manifest, isLoading }: ManifestViewerProps) {
  const [copied, setCopied] = useState(false);

  const handleCopyJSON = async () => {
    const json = JSON.stringify(manifest, null, 2);
    await navigator.clipboard.writeText(json);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const json = JSON.stringify(manifest, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'manifest.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <div className="text-center py-12 text-gray-500 dark:text-gray-400">
          Loading manifest...
        </div>
      </div>
    );
  }

  if (!manifest) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <div className="text-center py-12 text-gray-500 dark:text-gray-400">
          Manifest not available
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Actions Bar */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
        <div className="flex justify-between items-center">
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Raw Manifest JSON
            </h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
              Complete job metadata and processing results
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleCopyJSON}
              className="px-4 py-2 text-sm bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
            >
              {copied ? '✓ Copied' : '📋 Copy'}
            </button>
            <button
              onClick={handleDownloadJSON}
              className="px-4 py-2 text-sm bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-white rounded hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
            >
              ⬇️ Download
            </button>
          </div>
        </div>
      </div>

      {/* JSON Viewer */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow overflow-hidden">
        <div className="max-h-[800px] overflow-auto">
          <pre className="p-6 text-sm bg-gray-900 text-gray-100 overflow-x-auto">
            <code>{JSON.stringify(manifest, null, 2)}</code>
          </pre>
        </div>
      </div>

      {/* Info Panel */}
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
        <p className="text-sm text-blue-800 dark:text-blue-300">
          <strong>Note:</strong> This is the raw manifest.json file generated by the preprocessing pipeline.
          It contains all metadata, quality assessments, and file paths for the extracted content.
        </p>
      </div>
    </div>
  );
}
